https://codefresh.io/docker-tutorial/java_docker_pipeline/



#####################################################################################################################################################################
FROM alpine/git as clone
ARG url
WORKDIR /app
RUN git clone ${url}

FROM maven:3.5-jdk-8-alpine as build
ARG project
WORKDIR /app
COPY --from=clone /app/${project} /app
RUN mvn install

FROM openjdk:8-jre-alpine
WORKDIR /app
COPY --from=build /app/target/docker-spring-boot.jar /app
EXPOSE 8080
CMD java -jar docker-spring-boot.jar


#####################################################################################################################################################################
FROM openjdk:8
ADD target/docker-spring-boot.jar /usr/src/spring-boot-docker/docker-spring-boot.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar", "/usr/src/spring-boot-docker/docker-spring-boot.jar"]